### ISSUE TITLE
Cannot change dependencies of configuration ‘XXX’ after it has been included in dependency resolution.

### ISSUE THREAD

**Issue by hitYOUcry** [smallSohoSolo/McImage#64]
错误截图提示如下：
![image](https://user-images.githubusercontent.com/11732730/101971544-0650ea00-3c6d-11eb-90b6-e08ab4dde2c6.png)

![image](https://user-images.githubusercontent.com/11732730/101971569-34362e80-3c6d-11eb-8897-bc8c6c99a423.png)

看上去是插件内调用getDependencies出现异常，希望作者帮忙看看。（工程不引入mcImage模块时可以正常编译）

--------
Cannot change dependencies of configuration ':platform_service:common_widget:debugApi' after it has been included in dependency resolution.

--------
Caused by: org.gradle.api.internal.tasks.TaskDependencyResolveException: Could not determine the dependencies of task ':platform_service:social_lib:mergeDebugResources'.
	at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:66)
	at org.gradle.api.internal.tasks.AbstractTaskDependency.getDependencies(AbstractTaskDependency.java:42)
	at com.smallsoho.mcplugin.image.ImagePlugin$apply$1$1.execute(ImagePlugin.kt:115)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:158)
	at com.smallsoho.mcplugin.image.ImagePlugin$apply$1.execute(ImagePlugin.kt:61)
	at com.smallsoho.mcplugin.image.ImagePlugin$apply$1.execute(ImagePlugin.kt:16)

**Comment by hitYOUcry** [comment]
由于项目gradle版本原因，使用的mcimage为1.4.0版本

**Comment by smallSohoSolo** [comment]
麻烦提供下gradle 版本，我复现一下

**Comment by hitYOUcry** [comment]
https://services.gradle.org/distributions/gradle-4.10.1-all.zip

**Comment by huazhouwujinbiao** [comment]
我也遇到同样的问题，原因是：apply plugin: 'McImage'这个一定要写在apply plugin: 'kotlin-android'下面：
解决方法：
apply plugin: 'kotlin-android'
apply plugin: 'McImage'

**Comment by smallSohoSolo** [comment]
已解决，关闭了
